# Generated by Django 3.2.16 on 2022-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phn', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
